---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6

inputs:
  - name: dp-fastText

outputs:
  - name: build

run:
  path: dp-fastText/ci/scripts/build.sh
